package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"backend/graph/model"
	"context"
	"strconv"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, lname string) (*model.User, error) {
	var id int
	err := r.DB.QueryRow(
		"insert into users(name, lname) VALUES($1, $2) RETURNING id",
		name, lname,
	).Scan(&id)

	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:   strconv.Itoa(id),
		Name: name,
		Lname: lname,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	rows, err := r.DB.Query(
		"SELECT id, name, lname FROM users",
	)

	if err != nil {
		return nil, err
	}

	defer rows.Close()
	var users []*model.User

	for rows.Next() {
		var id int
		var name string
		var lname string

		rows.Scan(&id, &name, &lname)

		users = append(users, &model.User{
			ID:   strconv.Itoa(id),
			Name: name,
			Lname: lname,
		})

	}

	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
